spring.application.name=spring-ai-knowledge-assistant
spring.ai.openai.api-key=${OPENAI_API_KEY}
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/knowledgedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
